# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Computer Systems And Programming In C (RCS-101)
email: anubhavpatrick@gmail.com, anubhav.patrick@kiet.edu
description: > # this means to ignore newlines until "baseurl:"
  This portal is used for interaction with students taking the course Computer Systems and Programming in C taught at KIET Ghaziabad in semester I/II
baseurl: "" # the subpath of your site, e.g. /blog
url: "http:www.luckyexperience.com" # the base hostname & protocol for your site
# Build settings
markdown: kramdown
